In [1]:
# Importing libraries for the project
import os
import numpy as np
import pandas as pd
from matplotlib import pyplot
from scipy import optimize
import math

ModuleNotFoundError: No module named 'matplotlib'

In [2]:
filename = 'data/encodedShroomsV2.csv'
df = pd.read_csv(filename)
df

Empty DataFrame
Columns: [10010000001000000100001000000010100101000010000000010001000010001000100000000100000010001000001000100000000100, 00010000001000000000101000100000100110000010000000011000000010001000100000000100000010001000001000000100000010, 00000010001000010000001000010000100110000000001000011000000010001000100000000100000010001000001000000100000010, 10010000010000010000001000000010100101000000001000010001000010001000100000000100000010001000001000100000000100, 00010000001010000000010000000100101010000010000000100001000010001000100000000100000010001001000000000100010000, 00010000010000000000101000100000100110000000001000011000000010001000100000000100000010001000001000100000000010, 00000010001000010000001000100000100110100000000000011000000010001000100000000100000010001000001000100000000010, 00000010010000010000001000010000100110000000001000011000000010001000100000000100000010001000001000000100000100, 10010000010000010000001000000010100101000000000010010001000010001000100000000100000010001000001000100000001000, 00000010001000000000101000100000100110100000000000011000000010001000100000000100000010001000001000100000000100, 00010000010000000000101000010000100110100000000000011000000010001000100000000100000010001000001000000100000010, 00010000010000000000101000100000100110000000001000011000000010001000100000000100000010001000001000100000000100, 00000010001000000000101000100000100110000001000000011000000010001000100000000100000010001000001000000100000100, 10010000010000010000001000000010100101000010000000010001000010001000100000000100000010001000001000000100001000, 00010001000000000100010000000100101010000000001000100001000011000000100000000100000010001001000000100000010000, 00000101000010000000010000000100100101000010000000010001000010001000100000000100000010001000001000000100000001, 01000001000000010000010000000100101010000010000000100001000010001000100000000100000010001001000000000100010000, 10010000001000000100001000000010100101000000001000010001000010001000100000000100000010001000001000100000000100, 10010000010000010000001000000010100101000000001000010001000010001000100000000100000010001000001000000100000100, 10010000001000000100001000000010100101000010000000010001000010001000100000000100000010001000001000000100000100, 00000010001000000000101000100000100110000010000000011000000010001000100000000100000010001000001000000100000100, 10010000010000000100001000000010100101000000001000010001000010001000100000000100000010001000001000000100001000, 00000010010000000000101000010000100110000010000000011000000010001000100000000100000010001000001000000100000100, 00000010010000010000001000100000100110000001000000011000000010001000100000000100000010001000001000000100000010, 00000010001000010000001000010000100110100000000000011000000010001000100000000100000010001000001000100000000100, 11000000001000010000001000000010100101000000001000010001000010001000100000000100000010001000001000000100001000, 00010000010000000000101000100000100110000000001000011000000010001000100000000100000010001000001000000100000010, 00010000010000010000001000010000100110000001000000011000000010001000100000000100000010001000001000000100000010, 01000001000000000100010000000100100101000010000000010001000010001000100000000100000010001000001000100000000001, 00010000001000000000101000100000101001000000001000100000100010001000100000000100000010001000001000000100001000, 00000010001000000000101000010000100110100000000000011000000010001000100000000100000010001000001000000100000010, 10010000010000010000001000000010100101000010000000010001000010001000100000000100000010001000001000000100000100, 00010000010000000000101000010000100110000000001000011000000010001000100000000100000010001000001000000100000010, 00010000010000000100001000010000100110000000000010010100000010010000100000000100000010001000001000000100000001, 00000010010000000000101000010000100110000000001000011000000010001000100000000100000010001000001000000100000100, 000100010000000000001010000100001010010000010000001000

In [3]:
# initializing datasets, filling missing values with zeroes
train_size = 5700
X = np.empty((train_size, 109), dtype=int)
y = []
X_test = np.empty((8124-train_size, 109), dtype=int)
y_test = []
j = 0
for column in df:
    if j < train_size:
        if len(df[column].name) == 110:
            X_row = []
            if df[column].name[0] == '1':
                y.append(1)
            else:
                y.append(0)
        
            for i in range(110):
                if i > 0:
                    if df[column].name[i] == '1':
                        X_row.append(1)
                    else:
                        X_row.append(0)
            X[j] = X_row
        if len(df[column].name) == 112:
            X_row = []
            if df[column].name[0] == '1':
                y.append(1)
            else:
                y.append(0)
        
            for i in range(110):
                if i > 0:
                    if df[column].name[i] == '1':
                        X_row.append(1)
                    else:
                        X_row.append(0)
            X[j] = X_row
    else:
        if len(df[column].name) == 110:
            X_row = []
            if df[column].name[0] == '1':
                y_test.append(1)
            else:
                y_test.append(0)
        
            for i in range(110):
                if i > 0:
                    if df[column].name[i] == '1':
                        X_row.append(1)
                    else:
                        X_row.append(0)
            X_test[j-train_size] = X_row
        if len(df[column].name) == 112:
            X_row = []
            if df[column].name[0] == '1':
                y_test.append(1)
            else:
                y_test.append(0)
        
            for i in range(110):
                if i > 0:
                    if df[column].name[i] == '1':
                        X_row.append(1)
                    else:
                        X_row.append(0)
            X_test[j-train_size] = X_row
    j = j+1
        
y = np.array(y)
y_test = np.array(y_test)

In [4]:
X_test

array([[1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 1],
       [1, 0, 0, ..., 0, 0, 0],
       ...,
       [1, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0]])

In [5]:
y

array([1, 0, 0, ..., 1, 0, 1])

In [6]:
def sigmoid(z):
    """
    Compute sigmoid function given the input z.
    
    Parameters
    ----------
    z : array_like
        The input to the sigmoid function. This can be a 1-D vector 
        or a 2-D matrix. 
    
    Returns
    -------
    g : array_like
        The computed sigmoid function. g has the same shape as z, since
        the sigmoid is computed element-wise on z.
        
    Instructions
    ------------
    Compute the sigmoid of each value of z (z can be a matrix, vector or scalar).
    """
    # convert input to a numpy array
    z = np.array(z)
    
    # You need to return the following variables correctly 
    g = np.zeros(z.shape)

    # ====================== YOUR CODE HERE ======================

    g = 1 / (1 + np.exp(-z))

    # =============================================================
    return g

In [7]:
# Test the implementation of sigmoid function here
z = 0
g = sigmoid(z)

print('g(', z, ') = ', g)

g( 0 ) =  0.5


In [8]:
# Setup the data matrix appropriately, and add ones for the intercept term
m, n = (X.shape)

# Add intercept term to X
X = np.concatenate([np.ones((m, 1)), X], axis=1)

In [9]:
def costFunction(theta, X, y):
    """
    Compute cost and gradient for logistic regression. 
    
    Parameters
    ----------
    theta : array_like
        The parameters for logistic regression. This a vector
        of shape (n+1, ).
    
    X : array_like
        The input dataset of shape (m x n+1) where m is the total number
        of data points and n is the number of features. We assume the 
        intercept has already been added to the input.
    
    y : arra_like
        Labels for the input. This is a vector of shape (m, ).
    
    Returns
    -------
    J : float
        The computed value for the cost function. 
    
    grad : array_like
        A vector of shape (n+1, ) which is the gradient of the cost
        function with respect to theta, at the current values of theta.
        
    Instructions
    ------------
    Compute the cost of a particular choice of theta. You should set J to 
    the cost. Compute the partial derivatives and set grad to the partial
    derivatives of the cost w.r.t. each parameter in theta.
    """
    # Initialize some useful values
    m = y.size  # number of training examples

    # You need to return the following variables correctly 
    J = 0
    grad = np.zeros(theta.shape)

    # ====================== YOUR CODE HERE ======================
    h = sigmoid(X.dot(theta.T))
    
    J = (1 / m) * np.sum(-y.dot(np.log(h)) - (1 - y).dot(np.log(1 - h)))
    grad = (1 / m) * (h - y).dot(X)
    # =============================================================
    return J, grad

In [10]:
# Initialize fitting parameters
initial_theta = np.zeros(n+1)

cost, grad = costFunction(initial_theta, X, y)

print('Cost at initial theta (zeros): {:.3f}'.format(cost))
print('Expected cost (approx): 0.693\n')

print('Gradient at initial theta (zeros):')
print('\t[{:.4f}, {:.4f}, {:.4f}]'.format(*grad))

# Compute and display cost and gradient with non-zero theta
#test_theta = np.array([-24, 0.2, 0.2])
#cost, grad = costFunction(test_theta, X, y)

Cost at initial theta (zeros): 0.693
Expected cost (approx): 0.693

Gradient at initial theta (zeros):
	[0.1323, 0.0561, -0.0002]


In [11]:
# set options for optimize.minimize
options= {'maxiter': 400}

# see documention for scipy's optimize.minimize  for description about
# the different parameters
# The function returns an object `OptimizeResult`
# We use truncated Newton algorithm for optimization which is 
# equivalent to MATLAB's fminunc
# See https://stackoverflow.com/questions/18801002/fminunc-alternate-in-numpy
res = optimize.minimize(costFunction,
                        initial_theta,
                        (X, y),
                        jac=True,
                        method='TNC',
                        options=options)

# the fun property of `OptimizeResult` object returns
# the value of costFunction at optimized theta
cost = res.fun

# the optimized theta is in the x property
theta = res.x

# Print theta to screen
print('Cost at theta found by optimize.minimize: {:.3f}'.format(cost))
print('Expected cost (approx): 0.203\n');

print('theta:')
theta

Cost at theta found by optimize.minimize: 0.000
Expected cost (approx): 0.203

theta:


C:\Users\jethr\AppData\Local\Temp\ipykernel_21044\1102138006.py:44: RuntimeWarning: divide by zero encountered in log
  J = (1 / m) * np.sum(-y.dot(np.log(h)) - (1 - y).dot(np.log(1 - h)))


array([-0.26726649, -0.49165445,  1.08978153, -0.24105235, -0.71512327,
       -1.25025101,  1.3024348 , -2.1054249 ,  1.55358471,  0.22170961,
        0.07794947, -2.03090268,  0.71904091, -0.98064707, -0.96130752,
        1.88824978, -0.93476616, -0.51929348,  1.42515663,  1.52751135,
       -0.38935278, -0.13906157, -0.31870062,  5.7497105 ,  5.15691811,
        0.        , -6.11296616, -6.11296593,  1.49237288, -7.64978025,
        5.62935533,  1.70722951, -0.26726649,  0.        , -2.72487941,
        2.80230331, -3.6851398 ,  3.2964851 , -0.12160499, -0.1474192 ,
        1.29740058,  0.        , -0.80385717, -0.06877725, -0.41919668,
       -1.61089769, -1.03665186,  3.47344315, -0.87007628,  0.        ,
       -2.13565953,  1.81302292, -3.46591331, -2.63909773,  0.21298448,
        0.18531526,  5.04524541, -2.6192886 ,  5.70181176,  0.        ,
       -3.19135017, -2.50404763,  1.66735639,  1.71108334, -1.61513882,
        0.        , -0.8747143 ,  0.        ,  0.72369205, -1.33

In [12]:
def predict(theta, X):
    """
    Predict whether the label is 0 or 1 using learned logistic regression.
    Computes the predictions for X using a threshold at 0.5 
    (i.e., if sigmoid(theta.T*x) >= 0.5, predict 1)
    
    Parameters
    ----------
    theta : array_like
        Parameters for logistic regression. A vecotor of shape (n+1, ).
    
    X : array_like
        The data to use for computing predictions. The rows is the number 
        of points to compute predictions, and columns is the number of
        features.

    Returns
    -------
    p : array_like
        Predictions and 0 or 1 for each row in X. 
    
    Instructions
    ------------
    Complete the following code to make predictions using your learned 
    logistic regression parameters.You should set p to a vector of 0's and 1's    
    """
    m = X.shape[0] # Number of training examples

    # You need to return the following variables correctly
    p = np.zeros(m)

    # ====================== YOUR CODE HERE ======================
    p = np.round(sigmoid(X.dot(theta.T)))
    
    
    # ============================================================
    return p

In [13]:
test = np.column_stack((y_test, X_test))
#  Predict probability for a student with score 45 on exam 1 
#  and score 85 on exam 2 
prob = sigmoid(np.dot(list(test[4]), theta))
print('we predict an admission probability of {:.3f}'.format(prob))

# Compute accuracy on our training set
p = predict(theta, X)
print('Train Accuracy: {:.2f} %'.format(np.mean(p == y) * 100))

we predict an admission probability of 0.000
Train Accuracy: 100.00 %


In [14]:
score = 0
tot_prob = 0
for i in range(len(test)):
    prob = sigmoid(np.dot(list(test[i]), theta))
    if round(prob, 0) == 0:
        tot_prob = tot_prob + 1-prob
    else:
        tot_prob = tot_prob + prob
    if round(prob, 0) == y_test[i]:
        score = score + 1
tot_prob = tot_prob/len(test)
tot_prob

0.9889792966021409

In [15]:
score/len(test)

0.9257425742574258